#!/usr/bin/env bun

// used by ~/bin/ake and nushell completion

const HOME = process.env.HOME;
const PWD = process.env.PWD;

const DIRS = [
  `^(?<projectDir>${HOME}/dev/(?<projectFullName>(one|saber)/[^/]+))`, // ~/dev/ one/PROJECT
  `^(?<projectDir>${HOME}/dev/(?<projectFullName>[^/]+/[^/]+/[^/]+))`, // ~/dev/ WORK/COMPANY/PROJECT
  `^(?<projectDir>${HOME}/dev/(?<projectFullName>learn/testdir[^/]?))`, // ~/dev/ learn/testdirN
  `^(?<projectDir>${HOME}/(dev/)?(?<projectFullName>app/[^/]+))`, // ~/ app/PROJECT
].map((v) => new RegExp(v));

export function akeFindDir() {
  let found;
  for (const pattern of DIRS) {
    found = PWD.match(pattern)?.groups;
    if (found) {
      break;
    }
  }
  if (!found) {
    return {};
  }
  const { projectDir, projectFullName } = found;
  const akeUniqueName = `ake.${projectFullName.replaceAll("/", ".")}`;
  return { projectDir, projectFullName, akeUniqueName };
}

const isRunFromCLI = import.meta.url === `file://${process.argv[1]}`;
if (isRunFromCLI) {
  const { akeUniqueName } = akeFindDir();
  if (akeUniqueName) {
    console.log(akeUniqueName);
  }
}
